// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gserver/internal/store/ent/importtask"
	"gserver/internal/store/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ImportTaskQuery is the builder for querying ImportTask entities.
type ImportTaskQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ImportTask
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ImportTaskQuery builder.
func (itq *ImportTaskQuery) Where(ps ...predicate.ImportTask) *ImportTaskQuery {
	itq.predicates = append(itq.predicates, ps...)
	return itq
}

// Limit adds a limit step to the query.
func (itq *ImportTaskQuery) Limit(limit int) *ImportTaskQuery {
	itq.limit = &limit
	return itq
}

// Offset adds an offset step to the query.
func (itq *ImportTaskQuery) Offset(offset int) *ImportTaskQuery {
	itq.offset = &offset
	return itq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (itq *ImportTaskQuery) Unique(unique bool) *ImportTaskQuery {
	itq.unique = &unique
	return itq
}

// Order adds an order step to the query.
func (itq *ImportTaskQuery) Order(o ...OrderFunc) *ImportTaskQuery {
	itq.order = append(itq.order, o...)
	return itq
}

// First returns the first ImportTask entity from the query.
// Returns a *NotFoundError when no ImportTask was found.
func (itq *ImportTaskQuery) First(ctx context.Context) (*ImportTask, error) {
	nodes, err := itq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{importtask.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (itq *ImportTaskQuery) FirstX(ctx context.Context) *ImportTask {
	node, err := itq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ImportTask ID from the query.
// Returns a *NotFoundError when no ImportTask ID was found.
func (itq *ImportTaskQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = itq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{importtask.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (itq *ImportTaskQuery) FirstIDX(ctx context.Context) int {
	id, err := itq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ImportTask entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one ImportTask entity is not found.
// Returns a *NotFoundError when no ImportTask entities are found.
func (itq *ImportTaskQuery) Only(ctx context.Context) (*ImportTask, error) {
	nodes, err := itq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{importtask.Label}
	default:
		return nil, &NotSingularError{importtask.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (itq *ImportTaskQuery) OnlyX(ctx context.Context) *ImportTask {
	node, err := itq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ImportTask ID in the query.
// Returns a *NotSingularError when exactly one ImportTask ID is not found.
// Returns a *NotFoundError when no entities are found.
func (itq *ImportTaskQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = itq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{importtask.Label}
	default:
		err = &NotSingularError{importtask.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (itq *ImportTaskQuery) OnlyIDX(ctx context.Context) int {
	id, err := itq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ImportTasks.
func (itq *ImportTaskQuery) All(ctx context.Context) ([]*ImportTask, error) {
	if err := itq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return itq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (itq *ImportTaskQuery) AllX(ctx context.Context) []*ImportTask {
	nodes, err := itq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ImportTask IDs.
func (itq *ImportTaskQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := itq.Select(importtask.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (itq *ImportTaskQuery) IDsX(ctx context.Context) []int {
	ids, err := itq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (itq *ImportTaskQuery) Count(ctx context.Context) (int, error) {
	if err := itq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return itq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (itq *ImportTaskQuery) CountX(ctx context.Context) int {
	count, err := itq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (itq *ImportTaskQuery) Exist(ctx context.Context) (bool, error) {
	if err := itq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return itq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (itq *ImportTaskQuery) ExistX(ctx context.Context) bool {
	exist, err := itq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ImportTaskQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (itq *ImportTaskQuery) Clone() *ImportTaskQuery {
	if itq == nil {
		return nil
	}
	return &ImportTaskQuery{
		config:     itq.config,
		limit:      itq.limit,
		offset:     itq.offset,
		order:      append([]OrderFunc{}, itq.order...),
		predicates: append([]predicate.ImportTask{}, itq.predicates...),
		// clone intermediate query.
		sql:  itq.sql.Clone(),
		path: itq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID string `json:"uuid"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ImportTask.Query().
//		GroupBy(importtask.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (itq *ImportTaskQuery) GroupBy(field string, fields ...string) *ImportTaskGroupBy {
	group := &ImportTaskGroupBy{config: itq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := itq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return itq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID string `json:"uuid"`
//	}
//
//	client.ImportTask.Query().
//		Select(importtask.FieldUUID).
//		Scan(ctx, &v)
//
func (itq *ImportTaskQuery) Select(field string, fields ...string) *ImportTaskSelect {
	itq.fields = append([]string{field}, fields...)
	return &ImportTaskSelect{ImportTaskQuery: itq}
}

func (itq *ImportTaskQuery) prepareQuery(ctx context.Context) error {
	for _, f := range itq.fields {
		if !importtask.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if itq.path != nil {
		prev, err := itq.path(ctx)
		if err != nil {
			return err
		}
		itq.sql = prev
	}
	return nil
}

func (itq *ImportTaskQuery) sqlAll(ctx context.Context) ([]*ImportTask, error) {
	var (
		nodes = []*ImportTask{}
		_spec = itq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ImportTask{config: itq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, itq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (itq *ImportTaskQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := itq.querySpec()
	return sqlgraph.CountNodes(ctx, itq.driver, _spec)
}

func (itq *ImportTaskQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := itq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (itq *ImportTaskQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   importtask.Table,
			Columns: importtask.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: importtask.FieldID,
			},
		},
		From:   itq.sql,
		Unique: true,
	}
	if unique := itq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := itq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, importtask.FieldID)
		for i := range fields {
			if fields[i] != importtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := itq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := itq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := itq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := itq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (itq *ImportTaskQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(itq.driver.Dialect())
	t1 := builder.Table(importtask.Table)
	selector := builder.Select(t1.Columns(importtask.Columns...)...).From(t1)
	if itq.sql != nil {
		selector = itq.sql
		selector.Select(selector.Columns(importtask.Columns...)...)
	}
	for _, p := range itq.predicates {
		p(selector)
	}
	for _, p := range itq.order {
		p(selector)
	}
	if offset := itq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := itq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ImportTaskGroupBy is the group-by builder for ImportTask entities.
type ImportTaskGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (itgb *ImportTaskGroupBy) Aggregate(fns ...AggregateFunc) *ImportTaskGroupBy {
	itgb.fns = append(itgb.fns, fns...)
	return itgb
}

// Scan applies the group-by query and scans the result into the given value.
func (itgb *ImportTaskGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := itgb.path(ctx)
	if err != nil {
		return err
	}
	itgb.sql = query
	return itgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (itgb *ImportTaskGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := itgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (itgb *ImportTaskGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(itgb.fields) > 1 {
		return nil, errors.New("ent: ImportTaskGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := itgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (itgb *ImportTaskGroupBy) StringsX(ctx context.Context) []string {
	v, err := itgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (itgb *ImportTaskGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = itgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{importtask.Label}
	default:
		err = fmt.Errorf("ent: ImportTaskGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (itgb *ImportTaskGroupBy) StringX(ctx context.Context) string {
	v, err := itgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (itgb *ImportTaskGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(itgb.fields) > 1 {
		return nil, errors.New("ent: ImportTaskGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := itgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (itgb *ImportTaskGroupBy) IntsX(ctx context.Context) []int {
	v, err := itgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (itgb *ImportTaskGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = itgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{importtask.Label}
	default:
		err = fmt.Errorf("ent: ImportTaskGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (itgb *ImportTaskGroupBy) IntX(ctx context.Context) int {
	v, err := itgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (itgb *ImportTaskGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(itgb.fields) > 1 {
		return nil, errors.New("ent: ImportTaskGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := itgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (itgb *ImportTaskGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := itgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (itgb *ImportTaskGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = itgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{importtask.Label}
	default:
		err = fmt.Errorf("ent: ImportTaskGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (itgb *ImportTaskGroupBy) Float64X(ctx context.Context) float64 {
	v, err := itgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (itgb *ImportTaskGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(itgb.fields) > 1 {
		return nil, errors.New("ent: ImportTaskGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := itgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (itgb *ImportTaskGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := itgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (itgb *ImportTaskGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = itgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{importtask.Label}
	default:
		err = fmt.Errorf("ent: ImportTaskGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (itgb *ImportTaskGroupBy) BoolX(ctx context.Context) bool {
	v, err := itgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (itgb *ImportTaskGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range itgb.fields {
		if !importtask.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := itgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := itgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (itgb *ImportTaskGroupBy) sqlQuery() *sql.Selector {
	selector := itgb.sql
	columns := make([]string, 0, len(itgb.fields)+len(itgb.fns))
	columns = append(columns, itgb.fields...)
	for _, fn := range itgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(itgb.fields...)
}

// ImportTaskSelect is the builder for selecting fields of ImportTask entities.
type ImportTaskSelect struct {
	*ImportTaskQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (its *ImportTaskSelect) Scan(ctx context.Context, v interface{}) error {
	if err := its.prepareQuery(ctx); err != nil {
		return err
	}
	its.sql = its.ImportTaskQuery.sqlQuery(ctx)
	return its.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (its *ImportTaskSelect) ScanX(ctx context.Context, v interface{}) {
	if err := its.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (its *ImportTaskSelect) Strings(ctx context.Context) ([]string, error) {
	if len(its.fields) > 1 {
		return nil, errors.New("ent: ImportTaskSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := its.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (its *ImportTaskSelect) StringsX(ctx context.Context) []string {
	v, err := its.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (its *ImportTaskSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = its.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{importtask.Label}
	default:
		err = fmt.Errorf("ent: ImportTaskSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (its *ImportTaskSelect) StringX(ctx context.Context) string {
	v, err := its.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (its *ImportTaskSelect) Ints(ctx context.Context) ([]int, error) {
	if len(its.fields) > 1 {
		return nil, errors.New("ent: ImportTaskSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := its.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (its *ImportTaskSelect) IntsX(ctx context.Context) []int {
	v, err := its.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (its *ImportTaskSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = its.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{importtask.Label}
	default:
		err = fmt.Errorf("ent: ImportTaskSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (its *ImportTaskSelect) IntX(ctx context.Context) int {
	v, err := its.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (its *ImportTaskSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(its.fields) > 1 {
		return nil, errors.New("ent: ImportTaskSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := its.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (its *ImportTaskSelect) Float64sX(ctx context.Context) []float64 {
	v, err := its.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (its *ImportTaskSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = its.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{importtask.Label}
	default:
		err = fmt.Errorf("ent: ImportTaskSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (its *ImportTaskSelect) Float64X(ctx context.Context) float64 {
	v, err := its.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (its *ImportTaskSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(its.fields) > 1 {
		return nil, errors.New("ent: ImportTaskSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := its.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (its *ImportTaskSelect) BoolsX(ctx context.Context) []bool {
	v, err := its.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (its *ImportTaskSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = its.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{importtask.Label}
	default:
		err = fmt.Errorf("ent: ImportTaskSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (its *ImportTaskSelect) BoolX(ctx context.Context) bool {
	v, err := its.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (its *ImportTaskSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := its.sqlQuery().Query()
	if err := its.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (its *ImportTaskSelect) sqlQuery() sql.Querier {
	selector := its.sql
	selector.Select(selector.Columns(its.fields...)...)
	return selector
}
