// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"tkserver/internal/store/ent/kccoursesection"
	"tkserver/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KcCourseSectionDelete is the builder for deleting a KcCourseSection entity.
type KcCourseSectionDelete struct {
	config
	hooks    []Hook
	mutation *KcCourseSectionMutation
}

// Where adds a new predicate to the KcCourseSectionDelete builder.
func (kcsd *KcCourseSectionDelete) Where(ps ...predicate.KcCourseSection) *KcCourseSectionDelete {
	kcsd.mutation.predicates = append(kcsd.mutation.predicates, ps...)
	return kcsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (kcsd *KcCourseSectionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(kcsd.hooks) == 0 {
		affected, err = kcsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*KcCourseSectionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			kcsd.mutation = mutation
			affected, err = kcsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(kcsd.hooks) - 1; i >= 0; i-- {
			mut = kcsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, kcsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (kcsd *KcCourseSectionDelete) ExecX(ctx context.Context) int {
	n, err := kcsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (kcsd *KcCourseSectionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: kccoursesection.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: kccoursesection.FieldID,
			},
		},
	}
	if ps := kcsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, kcsd.driver, _spec)
}

// KcCourseSectionDeleteOne is the builder for deleting a single KcCourseSection entity.
type KcCourseSectionDeleteOne struct {
	kcsd *KcCourseSectionDelete
}

// Exec executes the deletion query.
func (kcsdo *KcCourseSectionDeleteOne) Exec(ctx context.Context) error {
	n, err := kcsdo.kcsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{kccoursesection.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (kcsdo *KcCourseSectionDeleteOne) ExecX(ctx context.Context) {
	kcsdo.kcsd.ExecX(ctx)
}
