// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"tkserver/internal/store/ent/predicate"
	"tkserver/internal/store/ent/tkexampaperpartitionscore"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TkExamPaperPartitionScoreDelete is the builder for deleting a TkExamPaperPartitionScore entity.
type TkExamPaperPartitionScoreDelete struct {
	config
	hooks    []Hook
	mutation *TkExamPaperPartitionScoreMutation
}

// Where adds a new predicate to the TkExamPaperPartitionScoreDelete builder.
func (teppsd *TkExamPaperPartitionScoreDelete) Where(ps ...predicate.TkExamPaperPartitionScore) *TkExamPaperPartitionScoreDelete {
	teppsd.mutation.predicates = append(teppsd.mutation.predicates, ps...)
	return teppsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (teppsd *TkExamPaperPartitionScoreDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(teppsd.hooks) == 0 {
		affected, err = teppsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TkExamPaperPartitionScoreMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			teppsd.mutation = mutation
			affected, err = teppsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(teppsd.hooks) - 1; i >= 0; i-- {
			mut = teppsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, teppsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (teppsd *TkExamPaperPartitionScoreDelete) ExecX(ctx context.Context) int {
	n, err := teppsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (teppsd *TkExamPaperPartitionScoreDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: tkexampaperpartitionscore.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tkexampaperpartitionscore.FieldID,
			},
		},
	}
	if ps := teppsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, teppsd.driver, _spec)
}

// TkExamPaperPartitionScoreDeleteOne is the builder for deleting a single TkExamPaperPartitionScore entity.
type TkExamPaperPartitionScoreDeleteOne struct {
	teppsd *TkExamPaperPartitionScoreDelete
}

// Exec executes the deletion query.
func (teppsdo *TkExamPaperPartitionScoreDeleteOne) Exec(ctx context.Context) error {
	n, err := teppsdo.teppsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tkexampaperpartitionscore.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (teppsdo *TkExamPaperPartitionScoreDeleteOne) ExecX(ctx context.Context) {
	teppsdo.teppsd.ExecX(ctx)
}
