// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"tkserver/internal/store/ent/predicate"
	"tkserver/internal/store/ent/tkquestion"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TkQuestionDelete is the builder for deleting a TkQuestion entity.
type TkQuestionDelete struct {
	config
	hooks    []Hook
	mutation *TkQuestionMutation
}

// Where adds a new predicate to the TkQuestionDelete builder.
func (tqd *TkQuestionDelete) Where(ps ...predicate.TkQuestion) *TkQuestionDelete {
	tqd.mutation.predicates = append(tqd.mutation.predicates, ps...)
	return tqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tqd *TkQuestionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tqd.hooks) == 0 {
		affected, err = tqd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TkQuestionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tqd.mutation = mutation
			affected, err = tqd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tqd.hooks) - 1; i >= 0; i-- {
			mut = tqd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tqd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tqd *TkQuestionDelete) ExecX(ctx context.Context) int {
	n, err := tqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tqd *TkQuestionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: tkquestion.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tkquestion.FieldID,
			},
		},
	}
	if ps := tqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tqd.driver, _spec)
}

// TkQuestionDeleteOne is the builder for deleting a single TkQuestion entity.
type TkQuestionDeleteOne struct {
	tqd *TkQuestionDelete
}

// Exec executes the deletion query.
func (tqdo *TkQuestionDeleteOne) Exec(ctx context.Context) error {
	n, err := tqdo.tqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tkquestion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tqdo *TkQuestionDeleteOne) ExecX(ctx context.Context) {
	tqdo.tqd.ExecX(ctx)
}
