// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"gserver/internal/store/ent/predicate"
	"gserver/internal/store/ent/useraskanswer"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserAskAnswerDelete is the builder for deleting a UserAskAnswer entity.
type UserAskAnswerDelete struct {
	config
	hooks    []Hook
	mutation *UserAskAnswerMutation
}

// Where adds a new predicate to the UserAskAnswerDelete builder.
func (uaad *UserAskAnswerDelete) Where(ps ...predicate.UserAskAnswer) *UserAskAnswerDelete {
	uaad.mutation.predicates = append(uaad.mutation.predicates, ps...)
	return uaad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uaad *UserAskAnswerDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uaad.hooks) == 0 {
		affected, err = uaad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserAskAnswerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uaad.mutation = mutation
			affected, err = uaad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uaad.hooks) - 1; i >= 0; i-- {
			mut = uaad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uaad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (uaad *UserAskAnswerDelete) ExecX(ctx context.Context) int {
	n, err := uaad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uaad *UserAskAnswerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: useraskanswer.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: useraskanswer.FieldID,
			},
		},
	}
	if ps := uaad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, uaad.driver, _spec)
}

// UserAskAnswerDeleteOne is the builder for deleting a single UserAskAnswer entity.
type UserAskAnswerDeleteOne struct {
	uaad *UserAskAnswerDelete
}

// Exec executes the deletion query.
func (uaado *UserAskAnswerDeleteOne) Exec(ctx context.Context) error {
	n, err := uaado.uaad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{useraskanswer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uaado *UserAskAnswerDeleteOne) ExecX(ctx context.Context) {
	uaado.uaad.ExecX(ctx)
}
