// Code generated by entc, DO NOT EDIT.

package tkuserrandomexamrecode

import (
	"time"

	"entgo.io/ent"
)

const (
	// Label holds the string label denoting the tkuserrandomexamrecode type in the database.
	Label = "tk_user_random_exam_recode"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldExamID holds the string denoting the exam_id field in the database.
	FieldExamID = "exam_id"
	// EdgeRandomExamQuestion holds the string denoting the random_exam_question edge name in mutations.
	EdgeRandomExamQuestion = "random_exam_question"
	// EdgeExamInfo holds the string denoting the exam_info edge name in mutations.
	EdgeExamInfo = "exam_info"
	// Table holds the table name of the tkuserrandomexamrecode in the database.
	Table = "tk_user_random_exam_recodes"
	// RandomExamQuestionTable is the table the holds the random_exam_question relation/edge. The primary key declared below.
	RandomExamQuestionTable = "tk_user_random_exam_recode_random_exam_question"
	// RandomExamQuestionInverseTable is the table name for the TkQuestion entity.
	// It exists in this package in order to avoid circular dependency with the "tkquestion" package.
	RandomExamQuestionInverseTable = "tk_questions"
	// ExamInfoTable is the table the holds the exam_info relation/edge.
	ExamInfoTable = "tk_user_random_exam_recodes"
	// ExamInfoInverseTable is the table name for the TkExamPaper entity.
	// It exists in this package in order to avoid circular dependency with the "tkexampaper" package.
	ExamInfoInverseTable = "tk_exam_papers"
	// ExamInfoColumn is the table column denoting the exam_info relation/edge.
	ExamInfoColumn = "exam_id"
)

// Columns holds all SQL columns for tkuserrandomexamrecode fields.
var Columns = []string{
	FieldID,
	FieldUUID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldUserID,
	FieldExamID,
}

var (
	// RandomExamQuestionPrimaryKey and RandomExamQuestionColumn2 are the table columns denoting the
	// primary key for the random_exam_question relation (M2M).
	RandomExamQuestionPrimaryKey = []string{"tk_user_random_exam_recode_id", "tk_question_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "gserver/internal/store/ent/runtime"
//
var (
	Hooks [1]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
