// Code generated by entc, DO NOT EDIT.

package kccoursechapter

const (
	// Label holds the string label denoting the kccoursechapter type in the database.
	Label = "kc_course_chapter"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCourseID holds the string denoting the course_id field in the database.
	FieldCourseID = "course_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// EdgeChapterCourse holds the string denoting the chapter_course edge name in mutations.
	EdgeChapterCourse = "chapter_course"
	// EdgeChapterSections holds the string denoting the chapter_sections edge name in mutations.
	EdgeChapterSections = "chapter_sections"
	// EdgeCourseSmallChapters holds the string denoting the course_small_chapters edge name in mutations.
	EdgeCourseSmallChapters = "course_small_chapters"
	// Table holds the table name of the kccoursechapter in the database.
	Table = "kc_course_chapters"
	// ChapterCourseTable is the table the holds the chapter_course relation/edge.
	ChapterCourseTable = "kc_course_chapters"
	// ChapterCourseInverseTable is the table name for the KcCourse entity.
	// It exists in this package in order to avoid circular dependency with the "kccourse" package.
	ChapterCourseInverseTable = "kc_courses"
	// ChapterCourseColumn is the table column denoting the chapter_course relation/edge.
	ChapterCourseColumn = "course_id"
	// ChapterSectionsTable is the table the holds the chapter_sections relation/edge.
	ChapterSectionsTable = "kc_course_sections"
	// ChapterSectionsInverseTable is the table name for the KcCourseSection entity.
	// It exists in this package in order to avoid circular dependency with the "kccoursesection" package.
	ChapterSectionsInverseTable = "kc_course_sections"
	// ChapterSectionsColumn is the table column denoting the chapter_sections relation/edge.
	ChapterSectionsColumn = "course_chapter_id"
	// CourseSmallChaptersTable is the table the holds the course_small_chapters relation/edge.
	CourseSmallChaptersTable = "kc_course_small_categories"
	// CourseSmallChaptersInverseTable is the table name for the KcCourseSmallCategory entity.
	// It exists in this package in order to avoid circular dependency with the "kccoursesmallcategory" package.
	CourseSmallChaptersInverseTable = "kc_course_small_categories"
	// CourseSmallChaptersColumn is the table column denoting the course_small_chapters relation/edge.
	CourseSmallChaptersColumn = "chapter_id"
)

// Columns holds all SQL columns for kccoursechapter fields.
var Columns = []string{
	FieldID,
	FieldCourseID,
	FieldTitle,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
)
